# Generated by Django 5.1 on 2024-08-29 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('totalSupply', models.DecimalField(decimal_places=10, max_digits=30)),
                ('volumeUSD', models.DecimalField(decimal_places=10, max_digits=30)),
                ('decimals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TokenHourData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=10, max_digits=30)),
                ('close', models.DecimalField(decimal_places=10, max_digits=30)),
                ('high', models.DecimalField(decimal_places=10, max_digits=30)),
                ('low', models.DecimalField(decimal_places=10, max_digits=30)),
                ('priceUSD', models.DecimalField(decimal_places=10, max_digits=30)),
                ('timestamp', models.DateTimeField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.token')),
            ],
        ),
    ]
