services:
  ############################################################
  # Django Services
  ############################################################
  .common-django-settings: &common-django-settings
    extends:
      service: sideshow-django-dev
      file: ../common/compose.yml
    volumes:
      - ../../:/app
    links:
      - psql
    env_file:
      - ../common/.env
      - ../dev/.env

  django_shell: # This is a one-shot command runner service, for manage.py or bash, it dies immediately
    <<: *common-django-settings
    environment:
      - SERVICE=django_shell
    command: "bash"
    entrypoint: []

  backend:
    <<: *common-django-settings
    ports:
      - "8833:8000"
    entrypoint: ["/app/infra/dev/entrypoint.sh"]
    command: ["/app/infra/dev/start-runserver.sh"]
    environment:
      - SERVICE=backend

  token_data:
    <<: *common-django-settings
    entrypoint: ["/app/infra/dev/entrypoint.sh"]
    command: ["python3", "sideshow/manage.py", "runscript", "token_data"]
    environment:
      - SERVICE=backend
      - KEEP_POLLING=1

  ############################################################
  # 3rd Party Services
  ############################################################
  psql:
    image: sameersbn/postgresql:14
    #ports: ['5432:5432'] # uncomment this to connect from a local desktop sql client
    expose: ["5432"] 

    environment:
      DB_NAME: sideshow
      DB_PASS: sideshow
      DB_USER: sideshow
    volumes:
      - /data/sideshow/postgresql:/var/lib/postgresql
